language: php

php:
  - 5.6

before_install:
  - sudo apt-get install -y libmcrypt-dev libreadline-dev libtidy-dev
install:
  - composer self-update
  - composer install --dev -n --prefer-source

script:
  - ./vendor/bin/phpunit
